[sync]
command:/usr/local/opnsense/scripts/OPNsense/ParentalControl/sync.php
parameters:
type:script
message:Applying parental control
description:Apply parental control device states

[status]
command:/usr/local/opnsense/scripts/OPNsense/ParentalControl/sync.php status
parameters:
type:script_output
message:Reading parental control status
